#! /bin/sh
# /etc/init.d/webcam

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting PWM_Controller"
    PWM_Controller
    ;;
  stop)
    echo "Stopping PWM_Controller"
    killall PWM_Controller
    ;;
  *)
    echo "Usage: /etc/init.d/PWM_Controllerd {start|stop}"
    exit 1
    ;;
esac

exit 0
